name: danbing
table: danbing
reader:
  name: pgsqlreader
  count: 0 
  conn:
    host: 127.0.0.01
    port: 9200
    user: elastic
    password: password
    db: 
  query:
    baseSQL: select * from danbing
    where: update
    primary: 
writer:
  name: streamwriter
  conn:
    host: 127.0.0.01
    port: 9200
    user: elastic
    password: password
    db: 
  query:
    baseSQL: 
    where:   
    primary: 
      - id 
speed: 
  thread: 100
  num_per_task: 100000 

log: info